language: shell

env:
  - CONDA_PYTHON = 3.8

os:
  - linux
  - windows
  - osx

before_install:
  # Set conda path info
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
  -   export MINICONDA_PATH=$HOME/miniconda;
  -   export MINICONDA_SUB_PATH=$MINICONDA_PATH/bin;
  - elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
  -   export MINICONDA_PATH=$HOME/miniconda;
  -   export MINICONDA_PATH_WIN=`cygpath --windows $MINICONDA_PATH`;
  -   export MINICONDA_SUB_PATH=$MINICONDA_PATH/Scripts;
  - fi;
  - export MINICONDA_LIB_BIN_PATH=$MINICONDA_PATH/Library/bin;
  # Obtain miniconda installer
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
  -   mkdir -p $HOME/download;
  -   if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  -     echo "downloading miniconda.sh for linux";
  -     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
  -   elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  -     echo "downloading miniconda.sh for osx";
  -     wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
  -   fi;
  - fi;
  # Install openssl for Windows
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
  -   choco install openssl.light;
  - fi;

install:
# begin installing miniconda
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
  -   echo "installing miniconda for posix";
  -   bash $HOME/download/miniconda.sh -b -u -p $MINICONDA_PATH;
  - elif  [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
  -   echo "folder $MINICONDA_SUB_PATH does not exist"
  -   echo "installing miniconda for windows";
  -   choco install miniconda3 --params="'/JustMe /AddToPath:1 /D:$MINICONDA_PATH_WIN'";
  - fi;

# end installing miniconda
  - export PATH="$MINICONDA_PATH:$MINICONDA_SUB_PATH:$MINICONDA_LIB_BIN_PATH:$PATH";

# begin checking miniconda existance
  - echo "checking if folder $MINICONDA_SUB_PATH exists"
  - if [[ -d $MINICONDA_SUB_PATH ]]; then
  -   echo "folder $MINICONDA_SUB_PATH exists"
  - else
  -   echo "folder $MINICONDA_SUB_PATH does not exist"
  - fi;

# end checking miniconda existance
  -  source $MINICONDA_PATH/etc/profile.d/conda.sh;
  -  hash -r;
  -  echo $TRAVIS_OS_NAME
  -  echo $CONDA_PYTHON
  -  python --version
  -  conda config --set always_yes yes --set changeps1 no;
  -  conda update -q conda;

# Useful for debugging any issues with conda
  -  conda info -a
  
# See if test-environment already available
# As necessary, apply python module recipies
  -  echo "create test-environment";
  -  conda env create -n test-environment -f ./tests/environment.${CONDA_PYTHON}.yml;
  -  conda activate test-environment
  -  conda list

script:
  - conda --version && python --version && pip --version