language: shell

jobs:
  include:
    - services: docker
    - os: osx
      language: shell
    - os: windows
      language: shell
    

before_install:
  - source ./ci/setup.sh

install:
  - source ./ci/install.sh

script:
  - pytest
  #- python -m cibuildwheel --output-dir wheelhouse