language: shell

env:
  - CONDA_PYTHON = 3.8

jobs:
  include:
    - services: docker
    - os: osx
      language: shell
    - os: windows
      language: shell
    

before_install:
  - source ./ci/setup.sh

install:
  - source ./ci/install.sh

script:
  - conda --version && python --version && pip --version
  - pytest
  - python -m cibuildwheel --output-dir wheelhouse