language: shell

env:
  - CONDA_PYTHON = 3.8

os:
  - linux
  - windows
  - osx

before_install:
  - source ./ci/setup.sh

install:
  - source ./ci/install.sh

script:
  - conda --version && python --version && pip --version