language: python
python: 3.8
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - libhdf5-dev

    - os: osx
      osx_image: xcode11
      language: shell
      addons:
        homebrew:
          packages:
          - hdf5
      before_install: python3 --version; pip3 --version

install:
  - source ./ci/install.sh

script:
  - pytest
  - python3 -m cibuildwheel --output-dir wheelhouse