reader:
  fname: data.out
  kind: lammps-data
  names: 
    - gel 
    - enzyme 
    - payload
  species: 
    1: 'monomer'
    2: 'monomer'
    3: 'enzyme'
    4: 'payload'
    5: 'unbonded'
    6: 'released'
  classes: [Gel]

diffusion_dictionary:
  'monomer':  0.01
  'unbonded': 0.01
  'released': 0.01
  'enzyme':   0.01
  'payload':  0.01

bonding:
  gel:
    - kind: harmonic
      species_1: 'monomer'
      species_2: 'monomer'
      length: 8.0
      force_constant: 1.0
    - kind: harmonic
      species_1: 'monomer'
      species_2: 'unbonded'
      length: 1.122
      force_constant: 0.0
    - kind: harmonic
      species_1: 'unbonded'
      species_2: 'unbonded'
      length: 1.122
      force_constant: 0.0
  
potentials:
  - kind: 'lj'
    atom_1: 'all'
    atom_2: 'all'
    epsilon: 1.0
    sigma: 1.0
    cutoff: 1.122

reaction:
  released: released
  enzyme: enzyme
  decay_rate: 1.
  degradation_rate: 1.
  radius: 1.0

simulation:
  timestep: 0.00012
  stride: 100
  length: 50
  box: [50, 50, 50]
   
  