enzymes: 100
molecules: 71
timestep: 0.0005
stride: 1000
length: 50000
reaction_radius: 2.0
reaction_rate: 10.0
spring_constant: 5.0
spring_length: 1.0
diffusion_dictionary:
  A: 1.0
  E: 1.0
  B: 1.0
  C: 1.0
box: 25.0
