folders:
  configuration: data
  topology: data
  bonds: data
  energy: data
  trajectory: data
  last: data
  input_file: generate/input_files
  micro_csd: generate/programs
  screen: logs
  forces: data
  
initial:
  box: 10
  N: 200
  crosslinker: 10
  configuration: oxdna.init.conf
  topology: oxdna.init.top
  bonds: oxdna.init.bonds
  input_file: generate
  seed: 1
  screen: init.screen

simulation:
  trajectory: oxdna.traj.conf
  last: oxdna.last.conf
  energy: oxdna.init.energy
  input_file: input
  seed: 1
  interval: 2000000
  steps: 10000000
  screen: simu.screen
  forces: oxdna.forces

main:
  configuration: oxdna.main.conf
  topology: oxdna.main.top
  bonds: oxdna.main.bonds
  input_file: convert
  screen: main.screen

programs:
  oxDNA: /rds/general/user/dm3613/home/software/oxDNA/build/bin/oxDNA
  DNAnalysis: /rds/general/user/dm3613/home/software/oxDNA/build/bin/DNAnalysis
  confGenerator: /rds/general/user/dm3613/home/software/oxDNA/build/bin/confGenerator
  micro_csd: 
    bin: micro_csd
    cpp: micro_csd.cpp
  compiler: g++
