# Builds using pip and tests using pytest

name: Docker

on:
  push:
    branches: master
    tags: v*.*

jobs:
  build:
    runs-on: docker
  env:
    LOCAL_IMAGE: hydrogels
    DOCKER_USER: debeshmandal
    DOCKER_REPO: hydrogels
  steps:
  - name: Login to DockerHub
    uses: docker/login-action@v1
    with:
      username: ${{ env.DOCKER_USER }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  - uses: actions/checkout@v2
  - name: Build docker image
    run: docker build . -t hydrogels
  - name: Label image (tag)
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    run: |
      export VERSION=`python -c "import hydrogels; print(hydrogels.__version__)"`
      echo "::set-env name=VERSION::$VERSION"
  - name: Label image (head)
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads')
    run: |
      echo "::set-env name=VERSION::dev"
  - name: Upload image
    run: |
      docker tag ${{ env.LOCAL_IMAGE }} ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:$VERSION
