# Builds using pip and tests using pytest

name: ManyLinux

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      PYTHON_BINARY_DIR: /opt/python/cp3${{matrix.minor_version}}-cp3${{matrix.minor_version}}/bin
    container: quay.io/pypa/${{matrix.image}}
    strategy:
      matrix:
        minor_version: [8]
        image: [manylinux2014_x86_64]

    steps:
    - name: show binary directory
      run: |
        ls /opt/python/*
        ls ${PYTHON_BINARY_DIR}
    - uses: actions/checkout@v2
    - name: Set up HDF5
      run: |
        yum install -y hdf5-devel
    - name: Install dependencies
      run: |
        ${PYTHON_BINARY_DIR}/pip install --upgrade pip setuptools wheel
        ${PYTHON_BINARY_DIR}/pip install numpy scipy pandas matplotlib pytest tqdm h5py pybind11 cmake starpolymers pytest auditwheel
    - name: Install readdy
      run: |
        pushd /tmp
        git clone https://github.com/readdy/readdy
        pushd readdy
        ${PYTHON_BINARY_DIR}/pip install .
        popd
        popd
    - name: Build and Install
      run: ${PYTHON_BINARY_DIR}/pip install .
    - name: Test
      run: ${PYTHON_BINARY_DIR}/pytest
    - name: Make wheel
      run: |
        mkdir -p /tmp/wheelhouse
        ${PYTHON_BINARY_DIR}/pip wheel --wheel-dir=/tmp/wheelhouse .
        ${PYTHON_BINARY_DIR}/auditwheel show /tmp/wheelhouse/*.whl
        ${PYTHON_BINARY_DIR}/auditwheel repair /tmp/wheelhouse/*.whl
        ls ./wheelhouse/
    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-wheel
        path: ./wheelhouse/*.whl
