# Builds using pip and tests using pytest

name: Coverage

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up HDF5
      run: |
        sudo apt-get -y install libhdf5-dev
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.py}}
    - name: Install dependencies
      run: |
        python -c "import sys; print(sys.path)" | sed "s/['|,]//g" | tr " " "\n"
        python -m pip install --upgrade pip setuptools wheel
        pip install numpy scipy pandas matplotlib pytest tqdm h5py cibuildwheel pybind11 cmake starpolymers pytest softnanotools networkx
        pip install pytest-cov
    - name: Install readdy
      run: |
        pushd /tmp
        git clone https://github.com/readdy/readdy
        pushd readdy
        git checkout v2.0.5
        pip install .
        popd
        popd
        python -c 'from readdy import *'
    - name: Coverage
      run: |
        pip install .
        export pythonversion=$(python -V | sed "s/Python //")
        pytest --import-mode=importlib --cov=/opt/hostedtoolcache/Python/$pythonversion/x64/lib/python3.8/site-packages/hydrogels --cov-report=xml
        sed -i 's/\/opt.*site-packages\///g' coverage.xml
        rm .coverage
        bash <(curl -s https://codecov.io/bash)
